INSERT INTO product_categories (name) VALUES
('Tools'),
('Adhesive & Silicon'),
('Paint'),
('Lacquer'),
('Primer, Thinner, and Turpentine'),
('Putty'),
('Others');

insert into suppliers (name) values ('Brainbox');
insert into suppliers (name) values ('Blognation');
insert into suppliers (name) values ('Wordware');
insert into suppliers (name) values ('Oyoba');
insert into suppliers (name) values ('Rooxo');
insert into suppliers (name) values ('Vidoo');
insert into suppliers (name) values ('Yambee');
insert into suppliers (name) values ('Oba');
insert into suppliers (name) values ('Centidel');
insert into suppliers (name) values ('Quinu');

insert into users (first_name, last_name, username, password, role) values ('Valeda', 'Heazel', 'vheazel0', 'rB7#!3}<6?t', 'Procurement');
insert into users (first_name, last_name, username, password, role) values ('Dannie', 'Rigg', 'drigg1', 'sD4)7wb<%G)j#3', 'Project');
insert into users (first_name, last_name, username, password, role) values ('Jase', 'Morrish', 'jmorrish2', 'dT8(vjU3fT', 'QS');
insert into users (first_name, last_name, username, password, role) values ('Catherina', 'Greenhow', 'cgreenhow3', 'hD5`&Qo5`', 'Procurement');
insert into users (first_name, last_name, username, password, role) values ('Sarette', 'Wackett', 'swackett4', 'eR1@T=/RM=iiIQy4', 'Procurement');
insert into users (first_name, last_name, username, password, role) values ('Kissiah', 'Guilliland', 'kguillil', 'mP0@j+d?L,@', 'QS');
insert into users (first_name, last_name, username, password, role) values ('Tildi', 'Farra', 'tfarra6', 'nX6!/DAa5s', 'Procurement');
insert into users (first_name, last_name, username, password, role) values ('Marcello', 'Vernalls', 'mvernalls7', 'gN6.XN!KO', 'Procurement');
insert into users (first_name, last_name, username, password, role) values ('Mollee', 'Josephsen', 'mjosephsen', 'jF6!HpKehR7tCrg', 'Project');
insert into users (first_name, last_name, username, password, role) values ('Celeste', 'Trevett', 'ctrevett9', 'gX9.3t|~J', 'QS');

insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CVZXHHWMZSDZBS5SSC2', 'Outdoor Picnic Blanket', 34.99, 'http://naver.com/interdum/mauris/ullamcorper/purus/sit/amet.jpg', 2, 6, 16, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CWR2XGNJJMEBSKFXQVZ', 'Vegan Tacos', 7.49, 'https://discuz.net/non/mi/integer/ac.html', 8, 5, 5, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CWSYDB1N9V9TF824M1K', 'Barbecue Chicken Pizza', 8.99, 'http://comsenz.com/nam.json', 7, 3, 4, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CWTGXZD86QAHBJAPVZX', 'Breathable Face Mask Set', 14.99, 'https://comsenz.com/sapien/urna/pretium/nisl.jsp', 5, 2, 7, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CWV4VY1E73CNK4GER4V', 'Electric Heat Pad', 24.99, 'https://yelp.com/nisl/duis/ac/nibh/fusce/lacus.js', 2, 2, 8, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CWVJ94HY4W3D5PE4XE6', 'Almond Butter Cookies', 4.49, 'http://nature.com/nec/euismod/scelerisque/quam.jpg', 9, 7, 16, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CWWY5K1BEZRFVPQBJ7W', 'Carrot Ginger Soup', 4.29, 'https://businessinsider.com/suspendisse.html', 3, 7, 11, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CWY4FNEMB4KJ61FSKNF', 'Pet Activity Tracker', 59.99, 'http://sogou.com/tortor/sollicitudin/mi.html', 10, 5, 3, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CWZX4AFX8BFS6VAQP21', 'Balsamic Salad Dressing', 2.99, 'http://diigo.com/ac/leo/pellentesque/ultrices.js', 3, 1, 6, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CWZPW6VB5HGJ6R2V2W4', 'Spiralizer', 22.99, 'https://hatena.ne.jp/pellentesque/at/nulla/suspendisse/potenti.html', 1, 6, 15, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CX0P30EZT0N12393076', 'Whole Chicken', 12.99, 'http://tripadvisor.com/praesent/blandit/lacinia/erat/vestibulum.html', 8, 2, 10, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CX1P9B3RRT2N5VR8M62', 'Lemon Basil Pasta Sauce', 4.99, 'http://ucsd.edu/dui/maecenas/tristique/est/et/tempus/semper.json', 7, 1, 17, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CX2VAVBZWJHX660DMPZ', 'Reusable Silicone Food Storage Bags', 19.99, 'https://domainmarket.com/praesent.jpg', 3, 1, 9, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CX3NKJN6FPEMP1ZAABV', 'Vegetable Broth', 2.29, 'http://utexas.edu/ultrices/posuere/cubilia/curae.aspx', 2, 1, 19, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CX3RGF8Y8WA4APDZG4G', 'Beef Enchilada Casserole', 8.99, 'https://google.fr/leo/rhoncus.js', 7, 2, 13, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CX4XY6P7223C1YMQE1S', 'Wall Calendar', 17.99, 'http://cbc.ca/faucibus.html', 1, 1, 4, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CX5SY00B7QQDTNFXFG9', 'Honey Mustard Pretzel Bites', 3.99, 'http://ezinearticles.com/ultrices.js', 8, 2, 6, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CX6C9FJ6VW5Q4WR862N', 'Jump Rope with Counter', 12.99, 'http://europa.eu/urna/ut/tellus/nulla/ut.html', 2, 1, 10, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CX6HTDD2P8Q161Y25M0', 'Silicone Baking Mat Set', 24.99, 'https://amazon.co.jp/aliquam/erat/volutpat/in/congue/etiam.aspx', 4, 4, 16, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CX73126V731QCAWXAZV', 'Mechanical Pencil Set', 19.99, 'https://yahoo.com/vestibulum/velit/id.html', 7, 4, 6, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CX8PPQ9SVJMEJ5NHEDQ', 'Silicone Baking Molds', 15.99, 'http://pcworld.com/nam/tristique/tortor.json', 6, 3, 6, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CX9FSEDB3PVFPSPDQC0', 'Wire Shelving Unit', 69.99, 'https://goo.gl/eu/sapien/cursus/vestibulum/proin/eu.html', 2, 6, 18, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXAKVGKPESE18WMFMTA', 'Cranberry Juice', 3.69, 'https://goo.gl/lobortis/ligula/sit/amet.jpg', 2, 4, 5, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXACP4MB8P3ZSQ8D0B1', 'Italian Herbal Seasoning', 1.99, 'http://si.edu/sed/lacus.json', 3, 3, 5, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXBC31NZHSF0T263WST', 'Baked Falafel Balls', 5.99, 'http://noaa.gov/odio/curabitur.png', 10, 6, 3, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXCD6B1JJZAA8SH26SF', 'Honey Sesame Cashews', 4.49, 'https://blogger.com/risus.xml', 3, 3, 0, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXDNFF8GMB93E0TGFT6', 'Car Escape Tool', 12.99, 'https://cdbaby.com/eu/tincidunt/in/leo.aspx', 5, 2, 14, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXD8E12ZTWGGW7NF23K', 'Quinoa & Black Bean Salad', 7.49, 'https://va.gov/vestibulum/sit/amet.jsp', 6, 7, 8, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXE6HNTHK37EK77NN85', 'DIY Lip Balm Making Kit', 22.99, 'http://last.fm/et/eros.html', 8, 4, 17, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXFFRX2F380G0JE65FQ', 'Sriracha Chili Sauce', 2.79, 'https://cnbc.com/dis/parturient/montes/nascetur/ridiculus/mus.aspx', 10, 5, 1, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXG2962WJ28VBJBDHB6', 'Peach Slices in Syrup', 2.59, 'https://mit.edu/ligula/sit/amet/eleifend/pede/libero.jpg', 8, 1, 14, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXG7BBN2G9X8STR4W9N', 'Tuscan Bean Soup', 2.49, 'http://cyberchimps.com/enim/leo/rhoncus/sed/vestibulum.xml', 2, 7, 16, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXHG3G75MTNR5B4B9R5', 'Mobile Workbench', 199.99, 'https://yolasite.com/erat/eros/viverra/eget.jpg', 4, 5, 3, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXJRS1HFECSQ2BKT2A8', 'Collapsible Colander', 14.99, 'https://opera.com/praesent/blandit/nam/nulla/integer/pede.jpg', 1, 1, 9, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXKVF2EFZT1GNBZRJZY', 'Organic Green Apples', 1.49, 'https://globo.com/pellentesque/quisque.js', 8, 4, 16, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXKWYTHH3F8CEEZ2MME', 'Kale Salad with Lemon Dressing', 4.99, 'http://berkeley.edu/felis.js', 10, 6, 15, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXMV1HVEZB7RZY7F62R', 'Pumpkin Spice Pancake Mix', 3.49, 'http://sourceforge.net/integer/non/velit/donec/diam/neque.json', 8, 4, 14, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXNC070YHF88C546W1W', 'Silicone Ice Cube Tray', 10.99, 'http://smugmug.com/eu/nibh/quisque.png', 2, 2, 20, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXPSGGBANDY125AJN3N', 'Granola Cereal', 4.49, 'https://tripadvisor.com/id/ornare/imperdiet.js', 9, 1, 6, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXQF8FV5983K4PQ8NN1', 'Marinara Parmesan Baked Ziti', 8.49, 'http://ebay.co.uk/vestibulum/ante.json', 10, 3, 1, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXQ3YH3F6X90XYX8648', 'Lightweight Rain Jacket', 79.99, 'http://vimeo.com/convallis/tortor.png', 7, 2, 8, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXRJWGNV96FYAVYQTWQ', 'White Rice', 1.49, 'https://bbb.org/metus/aenean/fermentum.jpg', 9, 2, 12, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXRXZPPAV9GBW2QT98Z', 'Lasagna Noodles', 1.89, 'http://i2i.jp/dapibus/nulla/suscipit/ligula/in/lacus.json', 3, 6, 18, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXSWCVF0YPQF848PV9V', 'Asian Stir-Fry Kit', 5.49, 'https://geocities.com/curabitur/gravida/nisi/at/nibh.png', 8, 7, 10, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXTRGWKEK02GBJQANH4', 'Organic Cucumber', 1.29, 'https://economist.com/morbi/a/ipsum.jpg', 5, 6, 19, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXVBG71J1MJ46V6ME8R', 'Teriyaki Chicken Wings', 10.99, 'http://buzzfeed.com/mus/etiam/vel/augue/vestibulum.json', 3, 5, 17, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXWFDX7SXDG81J8YJBY', 'Apple Pie Filling', 3.49, 'https://nsw.gov.au/suscipit.json', 3, 4, 20, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXWPW37SCGW7Y155VGG', 'Chicken Breasts', 9.99, 'https://posterous.com/nulla/suscipit/ligula/in/lacus/curabitur.xml', 8, 5, 11, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXX00D8X1QBSR9R5DQM', 'Pet Waterer with Filtration', 39.99, 'https://altervista.org/imperdiet/nullam/orci/pede/venenatis/non.html', 1, 1, 17, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXYKBCWWWBSAXDQRR6W', 'Baked Falafel', 5.49, 'http://plala.or.jp/justo/sit/amet/sapien/dignissim.jsp', 8, 3, 20, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CXZ4H46XW181T0DDX5P', 'Salt and Pepper Grinder Set', 19.99, 'https://nature.com/in/tempor.xml', 4, 4, 9, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY09YVQDEFRXE9DP3DM', 'Roasted Red Pepper Sauce', 3.29, 'http://ft.com/nulla/suspendisse/potenti/cras/in.jsp', 4, 4, 0, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY0HRX2WJZZ2G74K5YK', 'Frozen Hash Browns', 2.99, 'https://timesonline.co.uk/vivamus.jpg', 3, 4, 20, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY1J3S1GHN8D4J0DQC7', 'Garden Vegetable Chips', 3.49, 'http://shop-pro.jp/congue/diam/id/ornare.jpg', 4, 1, 5, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY2J424S8CCP2HCDJ1H', 'High-Speed Hand Blender', 39.99, 'http://sciencedaily.com/eu/magna/vulputate/luctus/cum.png', 8, 4, 5, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY3499NJ1VVDZT3MCDH', 'Teriyaki Tofu Stir-Fry', 7.49, 'http://dell.com/nisi.html', 3, 5, 6, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY32G37CJBYVQ2GVWR6', 'Handheld Garment Steamer', 34.99, 'https://auda.org.au/nonummy/maecenas/tincidunt.js', 10, 5, 11, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY4TMT77WJ30Z0PXB5R', 'Stainless Steel Cutlery Set', 29.99, 'http://ning.com/nulla/suscipit/ligula.json', 4, 4, 18, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY5AHF5B914HBNE05K4', 'Spicy Hummus', 3.49, 'http://harvard.edu/curae/mauris/viverra/diam/vitae.json', 4, 2, 15, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY60R624XP1XTWQVK6H', 'Canned Sardines', 3.29, 'https://goo.gl/magna/vulputate/luctus.jpg', 8, 2, 10, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY74H6MF0N2A79X3ZKY', 'Spicy Chicken Wings', 9.99, 'http://go.com/sit/amet/sapien.aspx', 2, 4, 15, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY78ZMTSMJPQJZ6H9CR', 'Dark Chocolate Almond Butter Cups', 4.99, 'https://latimes.com/tortor/id/nulla/ultrices.html', 8, 4, 19, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY8QR78ABTM7BHW1ZJ8', 'Personalized Pet ID Tags', 9.99, 'http://usda.gov/rutrum/nulla/nunc/purus/phasellus/in/felis.js', 4, 6, 7, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY9VC2QFES8ZJYGSF6Y', 'Coconut Oil', 6.49, 'http://craigslist.org/convallis/eget.xml', 10, 2, 5, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CY99NTX6RQZ6CG9H3TF', 'Organic Green Lentils', 3.99, 'https://sciencedaily.com/id/luctus/nec/molestie/sed/justo.jpg', 3, 2, 14, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYARDJMMYBR2GM1YACS', 'Portable Air Compressor', 44.99, 'http://altervista.org/sit/amet/nunc/viverra/dapibus/nulla/suscipit.xml', 3, 5, 6, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYBZ76GJFRSQS60M3HZ', 'Pineapple Chunks (canned)', 2.29, 'http://businesswire.com/praesent/blandit/lacinia/erat.jpg', 6, 4, 4, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYCP9WV5CQ4B2XCW7P7', 'Nature Explorer Lens Kit', 19.99, 'https://nytimes.com/donec/semper/sapien.png', 3, 5, 3, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYCN2P0ZXD8094MRW7J', 'Puzzle', 27.99, 'https://businesswire.com/elit/proin/interdum/mauris/non.html', 8, 4, 1, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYD577SBEGHASR3E0QM', 'Sliced Olives', 1.99, 'http://acquirethisname.com/bibendum/imperdiet/nullam/orci/pede.json', 8, 1, 19, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYEAPJXA8M6P9X37TN4', 'Compact Hair Dryer', 29.99, 'http://globo.com/amet/erat/nulla/tempus/vivamus.xml', 2, 7, 13, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYER1T2HWHC7R873G36', 'BBQ Sauce', 3.49, 'http://go.com/est/et/tempus/semper/est/quam.jpg', 4, 5, 0, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYFNYR7JZHSXPCRWSWG', 'Sliced Cucumbers', 1.29, 'https://feedburner.com/luctus/nec/molestie/sed.jpg', 3, 7, 19, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYGPDNBQ2GCPQD3EWT6', 'Roasted Garlic Aioli', 3.79, 'http://edublogs.org/ornare/imperdiet.xml', 7, 4, 1, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYHAGJ4EPR75XJW9C1M', 'Baking Soda', 0.99, 'http://msu.edu/eleifend/quam/a/odio/in/hac/habitasse.aspx', 8, 6, 12, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYH7ZQC9R56641CR2EN', 'Skincare Set', 54.99, 'http://dot.gov/primis/in/faucibus/orci/luctus/et/ultrices.jsp', 7, 2, 13, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYJQKF3XY2ZVTDJXEWT', 'Smartphone Projector', 29.99, 'http://imageshack.us/elit.png', 10, 5, 2, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYKEGJ8A3VHVCWWE21M', 'Beef Tacos', 5.49, 'http://shareasale.com/potenti/cras/in/purus/eu.html', 7, 4, 19, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYMQ584TEH7HEM2HRFB', 'Mini Hand Gesture Drone', 29.99, 'http://ibm.com/eleifend.xml', 5, 7, 10, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYM9QSNK58F7R1AQ3AH', 'High-Waisted Skirt', 34.99, 'http://cnn.com/arcu/libero/rutrum/ac/lobortis/vel/dapibus.aspx', 3, 5, 13, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYNH615RA3BC9DEN3W9', 'LED Strip Lights Kit', 29.99, 'http://fotki.com/massa.xml', 1, 6, 10, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYPTBWS72QY7F8ADSSV', 'Shower Curtain Hooks', 12.99, 'http://washington.edu/pede/ullamcorper/augue/a.aspx', 5, 5, 12, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYPQNR3C1QN58S0ET60', 'Wireless Keyboard and Mouse Combo', 34.99, 'https://google.pl/sociis/natoque.jsp', 6, 1, 0, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYQTA8MC8R5JDX2S8S5', 'Cocktail Shaker Set', 29.99, 'https://princeton.edu/sapien/ut/nunc/vestibulum.aspx', 5, 6, 16, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYRJYT06SM5G07HQ11Y', 'Folding Pocket Knife', 24.99, 'https://economist.com/volutpat/sapien/arcu/sed/augue.xml', 7, 2, 17, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYSVQ947QMHZNW65SZJ', 'Ethically-Sourced Coffee Beans', 9.99, 'https://mapy.cz/duis/aliquam.jpg', 7, 1, 10, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYS6BTJ3AE2G9D13456', 'Vegetable Lasagna', 6.99, 'http://huffingtonpost.com/cubilia/curae/nulla.js', 10, 7, 2, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYTRXM20A4MWJP88BCZ', 'Spinach Feta Wraps', 4.29, 'https://hao123.com/blandit/ultrices/enim/lorem/ipsum/dolor.json', 7, 1, 0, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYVT6Y897W54NVF8PQX', 'Fitness Mat', 49.99, 'https://xing.com/sit/amet/erat.png', 9, 5, 13, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYW747H3XAT14J89YK6', 'Classic White T-Shirt', 19.99, 'https://microsoft.com/in.js', 9, 3, 3, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYXPTJVNR7YRR3B0TXP', 'Classic Vanilla Fudge', 4.49, 'http://jugem.jp/ligula/suspendisse/ornare/consequat/lectus.aspx', 8, 6, 19, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYXMY9J5M3VRXRS8QVH', 'Green Smoothie Mix', 5.99, 'https://economist.com/id.jsp', 1, 4, 20, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CYYY63PV5ZSJB8C9F84', 'Mediterranean Couscous', 3.59, 'https://mediafire.com/id/ligula.js', 10, 2, 15, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CZ03FXK6EJQ4CFFMB0X', 'Baking Powder', 1.79, 'https://histats.com/elementum/ligula/vehicula/consequat/morbi.js', 5, 1, 14, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CZ1JRSNX2WZS2QZ2PYA', 'Pumpkin Spice Cookies', 3.29, 'https://indiatimes.com/sapien/a/libero/nam/dui/proin.js', 1, 3, 20, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CZ2FV2TK3QQWSKB6QS9', 'Electric Wine Opener', 29.99, 'https://symantec.com/semper/interdum/mauris/ullamcorper/purus/sit.js', 7, 1, 14, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CZ37KZ2FGZ7QT05XF93', 'Magnetic Phone Car Mount', 14.99, 'http://geocities.com/interdum/eu/tincidunt/in/leo/maecenas.json', 10, 1, 16, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CZ31NMKBJZKN1XCJP23', 'Portable Hammock Swing', 59.99, 'http://google.de/dui/luctus/rutrum/nulla/tellus/in.js', 4, 5, 20, true);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CZ49SFT3ZPXTQDVKQ01', 'Maple Cinnamon Granola', 4.29, 'http://tumblr.com/ullamcorper/purus.html', 7, 6, 15, false);
insert into products (product_id, name, cost, url, supplier_id, category_id, initial_quantity, disabled) values ('01KNNG2CZ5PAN3ARVMD7PTAA7Y', 'Deep Tissue Massage Gun', 89.99, 'https://cdbaby.com/eu.html', 6, 1, 3, true);

insert into delivery_orders (id, date) values ('SK9879', '2026-03-19');
insert into delivery_orders (id, date) values ('NH7905', '2024-01-04');
insert into delivery_orders (id, date) values ('NZ6489', '2024-04-19');
insert into delivery_orders (id, date) values ('AC3869', '2025-07-19');
insert into delivery_orders (id, date) values ('AF2174', '2025-12-25');
insert into delivery_orders (id, date) values ('AM3307', '2025-09-15');
insert into delivery_orders (id, date) values ('SQ3494', '2024-02-03');
insert into delivery_orders (id, date) values ('UA5107', '2025-04-28');
insert into delivery_orders (id, date) values ('AC9289', '2024-12-18');
insert into delivery_orders (id, date) values ('NZ8173', '2025-05-08');
insert into delivery_orders (id, date) values ('BA2372', '2025-07-16');
insert into delivery_orders (id, date) values ('IB8156', '2024-06-01');
insert into delivery_orders (id, date) values ('KE7203', '2026-02-14');
insert into delivery_orders (id, date) values ('TG2442', '2024-12-29');
insert into delivery_orders (id, date) values ('TG9073', '2025-03-31');
insert into delivery_orders (id, date) values ('NH2315', '2024-12-23');
insert into delivery_orders (id, date) values ('QR7511', '2025-06-22');
insert into delivery_orders (id, date) values ('NH7997', '2025-06-28');
insert into delivery_orders (id, date) values ('NH8525', '2025-08-30');
insert into delivery_orders (id, date) values ('BA9148', '2025-10-15');
insert into delivery_orders (id, date) values ('LA4744', '2024-07-06');
insert into delivery_orders (id, date) values ('QR6336', '2024-05-08');
insert into delivery_orders (id, date) values ('LH1464', '2024-05-19');
insert into delivery_orders (id, date) values ('TG5312', '2025-09-14');
insert into delivery_orders (id, date) values ('LA9322', '2025-12-20');
insert into delivery_orders (id, date) values ('DL2266', '2024-08-28');
insert into delivery_orders (id, date) values ('AI4444', '2025-11-08');
insert into delivery_orders (id, date) values ('NZ6454', '2024-07-03');
insert into delivery_orders (id, date) values ('DL2000', '2025-12-19');
insert into delivery_orders (id, date) values ('DL2657', '2026-02-10');
insert into delivery_orders (id, date) values ('NH4894', '2025-08-23');
insert into delivery_orders (id, date) values ('UA9032', '2025-03-26');
insert into delivery_orders (id, date) values ('AI6208', '2025-01-18');
insert into delivery_orders (id, date) values ('SA5035', '2025-01-26');
insert into delivery_orders (id, date) values ('AZ2773', '2024-12-17');
insert into delivery_orders (id, date) values ('AM7520', '2024-06-09');
insert into delivery_orders (id, date) values ('LH6904', '2026-01-23');
insert into delivery_orders (id, date) values ('CX6312', '2024-10-03');
insert into delivery_orders (id, date) values ('WN9242', '2025-06-01');
insert into delivery_orders (id, date) values ('SA1377', '2026-01-21');
insert into delivery_orders (id, date) values ('AC5992', '2025-08-15');
insert into delivery_orders (id, date) values ('AM3761', '2025-04-02');
insert into delivery_orders (id, date) values ('AZ2789', '2024-06-03');
insert into delivery_orders (id, date) values ('QR6570', '2025-03-17');
insert into delivery_orders (id, date) values ('UA1324', '2025-05-17');
insert into delivery_orders (id, date) values ('BA3224', '2026-02-24');
insert into delivery_orders (id, date) values ('LA3981', '2025-08-25');
insert into delivery_orders (id, date) values ('SK3399', '2026-03-30');
insert into delivery_orders (id, date) values ('AV7161', '2025-06-15');
insert into delivery_orders (id, date) values ('AV7276', '2025-04-25');

insert into transactions (created_at, logger_id, product_id, quantity_changed, delivery_id) values ('2026-03-19 20:42:52', 3, 48, 10, 'AV7276');
insert into transactions (created_at, logger_id, product_id, quantity_changed, delivery_id) values ('2025-11-11 20:48:23', 2, 50, 8, 'UA1324');
insert into transactions (created_at, logger_id, product_id, quantity_changed, delivery_id) values ('2024-08-19 14:49:35', 4, 98, 10, 'AZ2773');
insert into transactions (created_at, logger_id, product_id, quantity_changed, delivery_id) values ('2025-06-15 05:15:51', 2, 20, 3, 'AI4444');
insert into transactions (created_at, logger_id, product_id, quantity_changed, delivery_id) values ('2024-02-08 23:11:37', 6, 47, 8, 'TG9073');
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2024-04-09 14:17:34', 10, 51, -7);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2024-05-31 11:57:23', 7, 78, -7);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2024-08-30 22:30:35', 5, 2, -1);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2024-10-06 23:10:13', 7, 55, -4);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2026-02-02 15:06:12', 5, 33, -8);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2025-11-10 00:26:54', 6, 17, -7);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2026-01-13 10:05:50', 2, 60, -9);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2025-03-14 17:24:54', 7, 90, -1);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2024-04-08 18:51:38', 2, 48, -9);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2025-06-30 02:42:38', 9, 60, -9);