INSERT INTO product_categories (name) VALUES
('Tools'),
('Adhesive & Silicon'),
('Paint'),
('Lacquer'),
('Primer, Thinner, and Turpentine'),
('Putty'),
('Others');

insert into suppliers (name) values ('Brainbox');
insert into suppliers (name) values ('Blognation');
insert into suppliers (name) values ('Wordware');
insert into suppliers (name) values ('Oyoba');
insert into suppliers (name) values ('Rooxo');
insert into suppliers (name) values ('Vidoo');
insert into suppliers (name) values ('Yambee');
insert into suppliers (name) values ('Oba');
insert into suppliers (name) values ('Centidel');
insert into suppliers (name) values ('Quinu');

insert into users (first_name, last_name, username, password, role) values ('Valeda', 'Heazel', 'vheazel0', 'rB7#!3}<6?t', 'Procurement');
insert into users (first_name, last_name, username, password, role) values ('Dannie', 'Rigg', 'drigg1', 'sD4)7wb<%G)j#3', 'Project');
insert into users (first_name, last_name, username, password, role) values ('Jase', 'Morrish', 'jmorrish2', 'dT8(vjU3fT', 'QS');
insert into users (first_name, last_name, username, password, role) values ('Catherina', 'Greenhow', 'cgreenhow3', 'hD5`&Qo5`', 'Procurement');
insert into users (first_name, last_name, username, password, role) values ('Sarette', 'Wackett', 'swackett4', 'eR1@T=/RM=iiIQy4', 'Procurement');
insert into users (first_name, last_name, username, password, role) values ('Kissiah', 'Guilliland', 'kguillil', 'mP0@j+d?L,@', 'QS');
insert into users (first_name, last_name, username, password, role) values ('Tildi', 'Farra', 'tfarra6', 'nX6!/DAa5s', 'Procurement');
insert into users (first_name, last_name, username, password, role) values ('Marcello', 'Vernalls', 'mvernalls7', 'gN6.XN!KO', 'Procurement');
insert into users (first_name, last_name, username, password, role) values ('Mollee', 'Josephsen', 'mjosephsen', 'jF6!HpKehR7tCrg', 'Project');
insert into users (first_name, last_name, username, password, role) values ('Celeste', 'Trevett', 'ctrevett9', 'gX9.3t|~J', 'QS');

insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Organic Fruit Salad', 4.49, 'smh.com.au/lectus/pellentesque/at/nulla.jpg', 6, 4, 2, 2);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Veggie Burger Patties', 5.99, 'hc360.com/mauris/lacinia/sapien/quis/libero/nullam.js', 4, 6, 5, 5);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Instant Camera', 89.99, 'arstechnica.com/amet/turpis/elementum/ligula/vehicula/consequat/morbi.png', 10, 3, 28, 28);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Sriracha Chili Sauce', 2.79, 'mysql.com/libero/convallis/eget/eleifend/luctus.xml', 4, 7, 16, 16);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Honey Mustard Chicken Breasts', 8.99, 'biglobe.ne.jp/aliquet/massa/id.html', 1, 3, 9, 9);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Nut Butter Cups', 3.99, 'sakura.ne.jp/lacinia.jpg', 10, 6, 12, 12);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Sushi Rice', 3.99, 'fotki.com/consequat/varius.png', 8, 1, 28, 28);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Freestanding Wine Rack', 79.99, 'netscape.com/nibh/fusce/lacus/purus/aliquet/at/feugiat.jpg', 4, 7, 25, 25);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Bamboo Utensil Set', 14.99, 'yelp.com/faucibus/orci/luctus/et/ultrices/posuere/cubilia.json', 10, 4, 3, 3);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Matcha Green Tea Powder', 14.99, 'sakura.ne.jp/nulla/nunc/purus/phasellus/in/felis/donec.png', 5, 5, 26, 26);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Backpacking Tent', 109.99, 'msu.edu/massa/id.xml', 7, 5, 19, 19);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Faux Fur Throw Blanket', 39.99, 'dailymail.co.uk/potenti/nullam/porttitor/lacus/at.js', 8, 3, 29, 29);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Falafel Mix', 2.79, 'xrea.com/volutpat/quam/pede/lobortis.html', 1, 6, 3, 3);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Body Pillow Case', 14.99, 'ustream.tv/volutpat.xml', 7, 3, 24, 24);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Almond Joy Snack Bars', 2.99, 'chicagotribune.com/ipsum/dolor/sit.aspx', 1, 1, 7, 7);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Stylish Wide-Leg Trousers', 59.99, 'nytimes.com/cras/pellentesque/volutpat/dui/maecenas/tristique/est.png', 4, 7, 21, 21);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Pecan Nuts', 6.49, 'elpais.com/consequat/metus/sapien.js', 10, 7, 11, 11);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Handmade Soap Making Kit', 34.99, 'usnews.com/vestibulum/quam/sapien.aspx', 10, 7, 15, 15);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Caramel Apple Chips', 3.49, 'bizjournals.com/nunc/purus/phasellus/in/felis/donec.jsp', 10, 5, 9, 9);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Personal Blender', 39.99, 'nasa.gov/id/lobortis/convallis/tortor/risus/dapibus/augue.js', 7, 6, 17, 17);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Balsamic Salad Dressing', 2.99, 'photobucket.com/et/commodo.xml', 1, 4, 21, 21);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Energy Protein Bars', 2.29, 'clickbank.net/vel/enim/sit/amet/nunc/viverra/dapibus.jpg', 1, 6, 26, 26);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Strawberry Fruit Spread', 3.59, 'mapy.cz/consequat/metus.jpg', 9, 6, 29, 29);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Bluetooth Sleep Headphones', 29.99, 'purevolume.com/orci/pede/venenatis/non/sodales/sed.js', 8, 5, 19, 19);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Vanilla Almond Granola', 4.29, 'mlb.com/vestibulum/rutrum/rutrum/neque/aenean/auctor/gravida.xml', 4, 2, 19, 19);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Roasted Red Pepper Dip', 3.29, 'ehow.com/nullam.jpg', 5, 5, 11, 11);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Honeycrisp Apples', 1.89, 'myspace.com/nam/tristique/tortor.xml', 1, 6, 9, 9);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Fridge Magnet Set', 15.99, 'irs.gov/convallis/morbi/odio/odio/elementum/eu.png', 6, 2, 12, 12);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('LED Under Cabinet Lighting', 29.99, 'indiegogo.com/ornare/consequat/lectus/in/est.jpg', 4, 7, 28, 28);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Electric Opener for Jars and Bottles', 24.99, 'homestead.com/ligula.html', 6, 6, 9, 9);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Puffed Rice Cake', 2.49, 'typepad.com/pellentesque/ultrices/phasellus/id.jsp', 2, 1, 29, 29);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Electric Heat Pad', 24.99, 'ehow.com/eget/eleifend/luctus/ultricies/eu/nibh/quisque.xml', 10, 1, 13, 13);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Dark Chocolate Almond Butter Cups', 4.99, 'cocolog-nifty.com/nulla/suscipit/ligula/in/lacus/curabitur/at.html', 7, 3, 19, 19);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Electric Food Steamer', 59.99, 'guardian.co.uk/nibh.png', 9, 7, 29, 29);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Cinnamon Rolls', 4.49, 'msn.com/amet/nulla.aspx', 1, 7, 12, 12);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Outdoor Camping Hammock', 29.99, 'w3.org/blandit/lacinia.jsp', 7, 7, 17, 17);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Avocado Oil', 8.49, 'princeton.edu/convallis/eget/eleifend.html', 6, 4, 27, 27);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Watercolor Set', 19.99, 't.co/at/ipsum/ac/tellus/semper/interdum.js', 4, 4, 3, 3);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Mini Cordless Vacuum Cleaner', 45.99, 'amazon.com/morbi/vestibulum/velit/id/pretium/iaculis.html', 7, 6, 15, 15);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Over-The-Door Shoe Organizer', 25.99, 'mapy.cz/mauris/lacinia/sapien/quis/libero.xml', 7, 1, 18, 18);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Sunflower Seeds', 2.99, 'amazonaws.com/magna/vulputate/luctus.json', 8, 2, 23, 23);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Vegetable Stir-Fry Sauce', 3.49, 'mozilla.com/vehicula/condimentum/curabitur.jsp', 9, 7, 5, 5);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Luxury Bath Robe', 49.99, 'joomla.org/sem/sed/sagittis/nam/congue/risus/semper.aspx', 6, 2, 4, 4);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Portable Bluetooth Headphones', 79.99, 'businessinsider.com/augue/aliquam.aspx', 3, 1, 20, 20);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Hiking Gaiters', 29.99, 'quantcast.com/ac/diam/cras/pellentesque/volutpat.jpg', 9, 1, 16, 16);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Spicy Tuna Salad', 4.49, 'a8.net/nec.xml', 8, 3, 12, 12);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Chickpea Snack Mix', 3.49, 'fda.gov/donec/vitae/nisi/nam/ultrices/libero/non.aspx', 8, 5, 26, 26);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Set of Measuring Spoons', 12.99, 'about.me/vel/pede/morbi.js', 4, 1, 2, 2);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Smashed Avocado with Lime', 2.49, 'w3.org/nunc/vestibulum/ante/ipsum/primis/in/faucibus.js', 2, 2, 4, 4);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Organic Tomato Soup', 3.79, 'wikia.com/magna/vulputate/luctus.js', 10, 1, 3, 3);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Travel Mug with Leak-Proof Lid', 24.99, 'reverbnation.com/sem/duis/aliquam/convallis.xml', 10, 3, 9, 9);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Organic Whole Grain Oats', 2.49, 'sina.com.cn/ut/nulla/sed/accumsan/felis/ut.js', 3, 4, 13, 13);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Shatterproof Wine Glasses', 24.99, 'shop-pro.jp/diam.aspx', 10, 3, 5, 5);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Energy Bites', 3.99, 'liveinternet.ru/cursus/id/turpis/integer/aliquet.html', 7, 5, 12, 12);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Canvas High-Top Sneakers', 49.99, 'jugem.jp/nibh/in/quis/justo/maecenas/rhoncus/aliquam.json', 3, 6, 11, 11);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Pepper Jack Cheese Slices', 3.49, 'bluehost.com/massa/tempor/convallis.jsp', 10, 4, 20, 20);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Acoustic Guitar', 199.99, 'slideshare.net/vel/pede/morbi/porttitor.jpg', 1, 6, 10, 10);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Almond Coconut Granola', 3.99, 'reference.com/justo/morbi/ut/odio.aspx', 4, 5, 13, 13);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Cilantro Lime Rice', 2.99, 'delicious.com/sapien/arcu/sed/augue/aliquam/erat.xml', 4, 6, 20, 20);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Pet Grooming Gloves', 9.99, 'berkeley.edu/donec/diam/neque/vestibulum/eget/vulputate.jpg', 6, 2, 11, 11);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Mini Indoor Hydroponic Garden', 59.99, 'bloglovin.com/nulla/ultrices/aliquet.html', 7, 2, 27, 27);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Classic BBQ Sauce', 2.79, 'java.com/viverra/eget/congue/eget.js', 8, 4, 11, 11);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Nutritional Yeast', 3.59, 'hp.com/enim/sit.png', 6, 7, 11, 11);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Repair Tool Set for Home Improvement', 29.99, 'chronoengine.com/nullam/molestie/nibh/in/lectus/pellentesque.jsp', 1, 3, 11, 11);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Leather Wallet', 49.99, 'de.vu/orci/pede/venenatis/non/sodales/sed.xml', 9, 4, 12, 12);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Samsung Galaxy Smartwatch', 249.99, 'icio.us/mus/vivamus.jsp', 5, 3, 11, 11);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Peach Fruit Cups', 1.99, 'xing.com/turpis/elementum/ligula/vehicula/consequat/morbi.png', 6, 6, 4, 4);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Weighted Blanket for Adults', 59.99, 'digg.com/aliquam/quis/turpis/eget/elit/sodales/scelerisque.html', 10, 7, 16, 16);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Sun Protection Clothing', 44.99, 'loc.gov/dictumst/morbi/vestibulum/velit/id/pretium/iaculis.xml', 2, 4, 6, 6);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Rechargeable Hand Warmer', 22.99, 'dmoz.org/magna/vulputate/luctus/cum.aspx', 10, 6, 6, 6);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Ginger Turmeric Latte Mix', 5.29, 'desdev.cn/tortor.html', 5, 7, 12, 12);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Vegetable Chips', 3.99, 'berkeley.edu/sagittis/nam/congue.png', 3, 6, 9, 9);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Camping Lantern', 34.99, 'pagesperso-orange.fr/vestibulum/quam.html', 10, 3, 19, 19);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Wild Rice & Quinoa Mix', 2.99, 'shinystat.com/luctus/tincidunt/nulla/mollis/molestie/lorem/quisque.js', 3, 7, 28, 28);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Summer Tank Dress', 39.99, 'bloglovin.com/eu/interdum/eu/tincidunt/in/leo/maecenas.aspx', 8, 7, 2, 2);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Organic Coconut Yogurt', 4.49, 'microsoft.com/potenti/nullam/porttitor/lacus/at/turpis.json', 2, 3, 24, 24);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Sweet and Spicy Barbecue Sauce', 3.99, 'hao123.com/nisi/vulputate/nonummy/maecenas/tincidunt/lacus.html', 10, 6, 10, 10);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Interactive Robot Toy', 34.99, 'rambler.ru/accumsan/tortor/quis/turpis.html', 9, 6, 25, 25);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Craft Beer Mustard', 3.99, 'mashable.com/et/magnis/dis.jpg', 7, 1, 29, 29);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Sous Vide Cooker', 79.99, 'apache.org/in/hac/habitasse/platea/dictumst.jsp', 5, 6, 13, 13);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Oven-Baked Parmesan Zucchini', 4.99, 'sciencedaily.com/non/lectus.json', 3, 3, 18, 18);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Customizable Name Puzzle', 29.99, 'feedburner.com/mauris/laoreet/ut/rhoncus.jpg', 3, 4, 23, 23);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Sliced Ham', 5.49, 'mtv.com/neque.jsp', 2, 7, 12, 12);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Italian Meatballs', 8.49, 'spiegel.de/orci/luctus/et/ultrices.json', 1, 7, 19, 19);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Outdoor String Lights', 24.99, 'hibu.com/at/nulla/suspendisse/potenti/cras.aspx', 2, 6, 29, 29);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Portable Solar Phone Charger', 29.99, 'freewebs.com/aliquet.png', 3, 5, 1, 1);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Herb Drying Rack', 22.99, 'tiny.cc/felis/sed/lacus/morbi/sem/mauris.json', 4, 5, 29, 29);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Red Lentils', 1.99, 'topsy.com/ultrices/mattis/odio.html', 2, 5, 21, 21);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Mini Hand Gesture Drone', 29.99, 'sourceforge.net/sodales/scelerisque/mauris/sit/amet.jsp', 9, 5, 25, 25);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Applewood Smoked Bacon', 6.99, 'istockphoto.com/sapien/quis/libero/nullam.jsp', 2, 2, 29, 29);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Reversible Swimming Pool Lounger', 34.99, 'free.fr/luctus/et.js', 5, 2, 18, 18);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Eggs (dozen)', 2.99, 'sogou.com/mi/in.xml', 2, 5, 14, 14);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Coconut Curry Lentil Soup', 3.99, 'apple.com/in/tempus/sit.js', 10, 2, 16, 16);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Cinnamon Ice Cream', 4.99, 'apache.org/congue.xml', 5, 4, 26, 26);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Cotton Tote Bag Set', 29.99, 'accuweather.com/in/hac.jsp', 4, 5, 21, 21);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Baked Falafel Balls', 5.99, 'flavors.me/nulla/mollis/molestie.json', 5, 2, 17, 17);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Jasmine Rice', 2.39, 'skyrock.com/at/velit/eu.html', 3, 1, 22, 22);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Basic V-Neck T-Shirt', 19.99, 'privacy.gov.au/id.jsp', 3, 1, 16, 16);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Essential Oil Diffuser', 34.99, 'spiegel.de/ante/vestibulum/ante/ipsum.xml', 8, 2, 27, 27);
insert into products (name, cost, url, supplier_id, category_id, initial_quantity, current_quantity) values ('Buffalo Chicken Dip', 5.99, 'vkontakte.ru/velit/id.js', 2, 4, 8, 8);

insert into delivery_orders (id, date) values ('SK9879', '2026-03-19');
insert into delivery_orders (id, date) values ('NH7905', '2024-01-04');
insert into delivery_orders (id, date) values ('NZ6489', '2024-04-19');
insert into delivery_orders (id, date) values ('AC3869', '2025-07-19');
insert into delivery_orders (id, date) values ('AF2174', '2025-12-25');
insert into delivery_orders (id, date) values ('AM3307', '2025-09-15');
insert into delivery_orders (id, date) values ('SQ3494', '2024-02-03');
insert into delivery_orders (id, date) values ('UA5107', '2025-04-28');
insert into delivery_orders (id, date) values ('AC9289', '2024-12-18');
insert into delivery_orders (id, date) values ('NZ8173', '2025-05-08');
insert into delivery_orders (id, date) values ('BA2372', '2025-07-16');
insert into delivery_orders (id, date) values ('IB8156', '2024-06-01');
insert into delivery_orders (id, date) values ('KE7203', '2026-02-14');
insert into delivery_orders (id, date) values ('TG2442', '2024-12-29');
insert into delivery_orders (id, date) values ('TG9073', '2025-03-31');
insert into delivery_orders (id, date) values ('NH2315', '2024-12-23');
insert into delivery_orders (id, date) values ('QR7511', '2025-06-22');
insert into delivery_orders (id, date) values ('NH7997', '2025-06-28');
insert into delivery_orders (id, date) values ('NH8525', '2025-08-30');
insert into delivery_orders (id, date) values ('BA9148', '2025-10-15');
insert into delivery_orders (id, date) values ('LA4744', '2024-07-06');
insert into delivery_orders (id, date) values ('QR6336', '2024-05-08');
insert into delivery_orders (id, date) values ('LH1464', '2024-05-19');
insert into delivery_orders (id, date) values ('TG5312', '2025-09-14');
insert into delivery_orders (id, date) values ('LA9322', '2025-12-20');
insert into delivery_orders (id, date) values ('DL2266', '2024-08-28');
insert into delivery_orders (id, date) values ('AI4444', '2025-11-08');
insert into delivery_orders (id, date) values ('NZ6454', '2024-07-03');
insert into delivery_orders (id, date) values ('DL2000', '2025-12-19');
insert into delivery_orders (id, date) values ('DL2657', '2026-02-10');
insert into delivery_orders (id, date) values ('NH4894', '2025-08-23');
insert into delivery_orders (id, date) values ('UA9032', '2025-03-26');
insert into delivery_orders (id, date) values ('AI6208', '2025-01-18');
insert into delivery_orders (id, date) values ('SA5035', '2025-01-26');
insert into delivery_orders (id, date) values ('AZ2773', '2024-12-17');
insert into delivery_orders (id, date) values ('AM7520', '2024-06-09');
insert into delivery_orders (id, date) values ('LH6904', '2026-01-23');
insert into delivery_orders (id, date) values ('CX6312', '2024-10-03');
insert into delivery_orders (id, date) values ('WN9242', '2025-06-01');
insert into delivery_orders (id, date) values ('SA1377', '2026-01-21');
insert into delivery_orders (id, date) values ('AC5992', '2025-08-15');
insert into delivery_orders (id, date) values ('AM3761', '2025-04-02');
insert into delivery_orders (id, date) values ('AZ2789', '2024-06-03');
insert into delivery_orders (id, date) values ('QR6570', '2025-03-17');
insert into delivery_orders (id, date) values ('UA1324', '2025-05-17');
insert into delivery_orders (id, date) values ('BA3224', '2026-02-24');
insert into delivery_orders (id, date) values ('LA3981', '2025-08-25');
insert into delivery_orders (id, date) values ('SK3399', '2026-03-30');
insert into delivery_orders (id, date) values ('AV7161', '2025-06-15');
insert into delivery_orders (id, date) values ('AV7276', '2025-04-25');

insert into transactions (created_at, logger_id, product_id, quantity_changed, delivery_id) values ('2026-03-19 20:42:52', 3, 48, 10, 'AV7276');
insert into transactions (created_at, logger_id, product_id, quantity_changed, delivery_id) values ('2025-11-11 20:48:23', 2, 50, 8, 'UA1324');
insert into transactions (created_at, logger_id, product_id, quantity_changed, delivery_id) values ('2024-08-19 14:49:35', 4, 98, 10, 'AZ2773');
insert into transactions (created_at, logger_id, product_id, quantity_changed, delivery_id) values ('2025-06-15 05:15:51', 2, 20, 3, 'AI4444');
insert into transactions (created_at, logger_id, product_id, quantity_changed, delivery_id) values ('2024-02-08 23:11:37', 6, 47, 8, 'TG9073');
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2024-04-09 14:17:34', 10, 51, -7);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2024-05-31 11:57:23', 7, 78, -7);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2024-08-30 22:30:35', 5, 2, -1);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2024-10-06 23:10:13', 7, 55, -4);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2026-02-02 15:06:12', 5, 33, -8);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2025-11-10 00:26:54', 6, 17, -7);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2026-01-13 10:05:50', 2, 60, -9);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2025-03-14 17:24:54', 7, 90, -1);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2024-04-08 18:51:38', 2, 48, -9);
insert into transactions (created_at, logger_id, product_id, quantity_changed) values ('2025-06-30 02:42:38', 9, 60, -9);